Export max_fee, nonce and signature to AccountParams struct
starkware-libs/starknet-api pull request #106
Opened 2023-07-24 12:38 UTC by MohammadNassar1

2023-07-24 12:51 UTC, yair-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-Na6wqfFDU7YcdOld0CD:-Na6wqfFDU7YcdOld0CE:b-61hamg) (no related file):*
Please add new transaction versions in a separate PR

___


<!-- Sent from Reviewable.io -->

2023-07-24 13:12 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-Na6wqfFDU7YcdOld0CD:-Na70sq76CUloRgPE7lH:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add new transaction versions in a separate PR
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-07-25 11:01 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaBdUjNDwBbQ7MLJC9W:b-4oacd9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
> ```XML
>         })*
>     };
> }
> ```

Why is it needed? To avoid repeating the `clone()`?



_Code quote:_
```XML
macro_rules! implement_account_params_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            self.$field.clone()
        })*
    };
}
```
___
*[`src/transaction.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBgL9E95riN-XzTu4D:-NaBgL9E95riN-XzTu4E:b-8i307o) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L123)):*
> ```XML
>                     Self::V2(tx) => &tx.account_params.$internal,
>                 }
>             }
> ```

Can it be a separate macro? 



_Code quote:_
```XML
            pub fn $internal(&self) -> &$int_field_type {
                match self {
                    Self::V0(tx) => &tx.account_params.$internal,
                    Self::V1(tx) => &tx.account_params.$internal,
                    Self::V2(tx) => &tx.account_params.$internal,
                }
            }
```
___
*[`src/transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBeS3K-srkI0TW2BdZ:-NaBeS3K-srkI0TW2Bd_:b-ec9y42) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L170)):*
> ```XML
> pub enum DeployAccountTransaction {
>     V1(DeployAccountTransactionV1),
> }
> ```

Can you please revert the changes RE deploy account version?



_Code quote:_
```XML
#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub enum DeployAccountTransaction {
    V1(DeployAccountTransactionV1),
}
```
___
*[`src/transaction.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBep5GDUo-3Cz6H1lj:-NaBep5GDUo-3Cz6H1lk:b2je8ky) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L281)):*
> ```XML
>             Self::V1(tx) => Some(&tx.account_params.nonce),
>         }
>     }
> ```

Maybe throw an error with the following description: "An InvokeFunction transaction (version = 0) cannot have a nonce."



_Suggestion:_
```XML
    pub fn nonce(&self) -> Nonce {
        match self {
            Self::V0(_tx) => Err(StarknetApiError::InvalidTransactionNonce),
            Self::V1(tx) => tx.account_params.nonce.clone(),
        }
    }
```


<!-- Sent from Reviewable.io -->

2023-07-25 12:13 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaBp19qCROf5TyJIVy7:bttfihb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed? To avoid repeating the `clone()`?
</blockquote></details>

In case we want to generalize the struct, it's better to have getter functions.
___
*[`src/transaction.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBgL9E95riN-XzTu4D:-NaBp0HLBtISxskxGZzM:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L123)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can it be a separate macro? 
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBeS3K-srkI0TW2BdZ:-NaBp-Je3KJavuC9wyWh:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L170)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please revert the changes RE deploy account version?
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBep5GDUo-3Cz6H1lj:-NaBofxPBqZ2WEPsNha0:bcbllrk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L281)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe throw an error with the following description: "An InvokeFunction transaction (version = 0) cannot have a nonce."
</blockquote></details>

I noticed that we use `Nonce::default()` in blockifier code for `InvokeTransactionV0`, so I changed the code accordingly.


<!-- Sent from Reviewable.io -->

2023-07-25 13:28 UTC, noaov1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaC085l6XEOgx3XGiXd:by1hi68) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In case we want to generalize the struct, it's better to have getter functions.
</blockquote></details>

Generalize in what way?
___
*[`src/transaction.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBep5GDUo-3Cz6H1lj:-NaCBXpRDqw9ck5iD7CM:b-5ycdns) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L281)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I noticed that we use `Nonce::default()` in blockifier code for `InvokeTransactionV0`, so I changed the code accordingly.
</blockquote></details>

It is a bit similar to the `compiled_class_hash` field in declare V2, where we simply don't have a getter. 
It can be confusing to get a default nonce while there is no nonce field. (In the blockifier repo we insert it into the `AccountTransactionContext` struct and we know that this field will not be used for V0 txs.)
___
*[`src/transaction.rs` line 136 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC7Lj_9FzWHcGfIYxN:-NaC7Lja7F4-7Ly8qo53:bitc55h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L136)):*
> ```XML
> //         )*
> //     };
> // }
> ```

Delete please :)



_Code quote:_
```XML
// macro_rules! implement_declare_tx_getters {
//     (account_params: $(($internal:ident, $int_field_type:ty)),* ; $(($field:ident,
// $field_type:ty)),*) => {         $(
//             // Getter for internal account_params fields
//             pub fn $internal(&self) -> &$int_field_type {
//                 match self {
//                     Self::V0(tx) => &tx.account_params.$internal,
//                     Self::V1(tx) => &tx.account_params.$internal,
//                     Self::V2(tx) => &tx.account_params.$internal,
//                 }
//             }
//         )*
//         $(
//             // Getter for external fields
//             pub fn $field(&self) -> &$field_type {
//                 match self {
//                     Self::V0(tx) => &tx.$field,
//                     Self::V1(tx) => &tx.$field,
//                     Self::V2(tx) => &tx.$field,
//                 }
//             }
//         )*
//     };
// }
```
___
*[`src/transaction.rs` line 138 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC8mXzAbAiDWr-Kakl:-NaC8mXzAbAiDWr-Kakm:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L138)):*
> ```XML
> // }
> 
> macro_rules! implement_declare_tx_internal_getters {
> ```





_Suggestion:_
```XML
macro_rules! implement_declare_tx_account_params_getters
```
___
*[`src/transaction.rs` line 156 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9Owb6Fd-1Thv4uvH:-NaC9Owb6Fd-1Thv4uvI:b-4tdgkt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L156)):*
> ```XML
>     ($(($field:ident, $field_type:ty)),*) => {
>         $(
>             // Getter for external fields
> ```

Same for other transaction types.
___
*[`src/transaction.rs` line 213 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9-EsAG4NSRpvfcwh:-NaC9-EsAG4NSRpvfcwi:bitc55h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L213)):*
> ```XML
> //         )*
> //     };
> // }
> ```

Delete please :)



_Code quote:_
```XML
// macro_rules! implement_deploy_account_tx_getters {
//     (account_params: $(($internal:ident, $int_field_type:ty)),* ; $(($field:ident,
// $field_type:ty)),*) => {         $(
//             // Getter for internal account_params fields
//             pub fn $internal(&self) -> $int_field_type {
//                 self.account_params.$internal.clone()
//             }
//         )*
//         $(
//             // Getter for external fields
//             pub fn $field(&self) -> $field_type {
//                 self.$field.clone()
//             }
//         )*
//     };
// }
```
___
*[`src/transaction.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC93It-jeenjWEWEWd:-NaC93It-jeenjWEWEWe:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L215)):*
> ```XML
> // }
> 
> macro_rules! implement_deploy_account_tx_internal_getters {
> ```





_Suggestion:_
```XML
macro_rules! implement_deploy_account_tx_account_params_getters
```
___
*[`src/transaction.rs` line 305 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9AuN7B19u5SSN2gH:-NaC9AuN7B19u5SSN2gI:bitc55h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L305)):*
> ```XML
> //         )*
> //     };
> // }
> ```

Delete please :)



_Code quote:_
```XML
// macro_rules! implement_invoke_tx_getters {
//     (account_params: $(($internal:ident, $int_field_type:ty)),* ;
//      $(($field:ident, $field_type:ty)),*) => {
//         $(
//             // Getter for internal account_params fields
//             pub fn $internal(&self) -> $int_field_type {
//                 match self {
//                     Self::V0(tx) => tx.$internal.clone(),
//                     Self::V1(tx) => tx.account_params.$internal.clone(),
//                 }
//             }
//         )*
//         $(
//             // Getter for external fields
//             pub fn $field(&self) -> $field_type {
//                 match self {
//                     Self::V0(tx) => tx.$field.clone(),
//                     Self::V1(tx) => tx.$field.clone(),
//                 }
//             }
//         )*
//     };
// }
```
___
*[`src/transaction.rs` line 337 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9iSY2r_yK1861IZj:-NaC9iSY2r_yK1861IZk:b7znp5d) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L337)):*
> ```XML
> impl InvokeTransaction {
>     implement_invoke_tx_internal_getters!((max_fee, Fee), (signature, TransactionSignature));
>     implement_invoke_tx_getters!((calldata, Calldata));
> ```

Add `sender_address`? (in invoke V0 it is the `contract_address` field)
WDYT @yair-starkware ?



_Code quote:_
```XML
implement_invoke_tx_getters!((calldata, Calldata));
```


<!-- Sent from Reviewable.io -->

2023-07-25 13:30 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: all files reviewed, 10 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)



<!-- Sent from Reviewable.io -->

2023-07-25 18:13 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaCMqQL8llZtwpMTo8z:bzeau8t) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Generalize in what way?
</blockquote></details>

For example, if we have a nested struct, we won't need to update our code in the blockifier repository. The changes will be transparent and seamlessly integrated.
___
*[`src/transaction.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBep5GDUo-3Cz6H1lj:-NaD-iNpBHUS8YrOsLnh:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L281)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is a bit similar to the `compiled_class_hash` field in declare V2, where we simply don't have a getter. 
It can be confusing to get a default nonce while there is no nonce field. (In the blockifier repo we insert it into the `AccountTransactionContext` struct and we know that this field will not be used for V0 txs.)
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 136 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC7Lj_9FzWHcGfIYxN:-NaCNB0F7o47dDIVjsvu:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Delete please :)
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 138 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC8mXzAbAiDWr-Kakl:-NaCv0UY50V2x95i0plQ:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L138)):*
> ```XML
> // }
> 
> macro_rules! implement_declare_tx_internal_getters {
> ```

Done.
___
*[`src/transaction.rs` line 156 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9Owb6Fd-1Thv4uvH:-NaCvD2Y6Yo6xOBK24_2:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L156)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same for other transaction types.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 213 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9-EsAG4NSRpvfcwh:-NaCvDpt8MnEQZKLPrLP:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L213)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Delete please :)
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC93It-jeenjWEWEWd:-NaCvFJB25nGyHAVYE05:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L215)):*
> ```XML
> // }
> 
> macro_rules! implement_deploy_account_tx_internal_getters {
> ```

Done.
___
*[`src/transaction.rs` line 305 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9AuN7B19u5SSN2gH:-NaCvFqdCYMe2k7XtNoy:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L305)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Delete please :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-26 08:07 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaGCKKX6Xb-uVptQmF4:btdsfzr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

For example, if we have a nested struct, we won't need to update our code in the blockifier repository. The changes will be transparent and seamlessly integrated.
</blockquote></details>

I see.
___
*[`src/transaction.rs` line 269 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGE5DE5jd_BMi7_tGw:-NaGE5DE5jd_BMi7_tGx:b3kre) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L269)):*
> ```XML
>         match self {
>             Self::V0(_) => Err(StarknetApiError::InvalidTransactionNonce),
>             Self::V1(tx) => Ok(tx.account_params.nonce),
> ```

?



_Suggestion:_
```XML
Self::V1(tx) => Ok(tx.account_params.nonce.clone()),
```
___
*[`src/transaction.rs` line 274 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGDt4O8Zv4s5vkCYsN:-NaGDt4O8Zv4s5vkCYsO:b-ssn05l) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L274)):*
> ```XML
>     pub fn account_params(&self) -> Result<AccountParams, StarknetApiError> {
>         match self {
>             Self::V0(_) => Err(StarknetApiError::InvalidTransactionNonce),
> ```

Is that the behaviour we want?



_Code quote:_
```XML
Self::V0(_) => Err(StarknetApiError::InvalidTransactionNonce),
```


<!-- Sent from Reviewable.io -->

2023-07-26 09:49 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 125 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGZzJw5EMKzKKJCBQ1:-NaGZzJw5EMKzKKJCBQ2:bbr15dw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L125)):*
> ```XML
>         )*
>     };
> }
> ```

And then you can have one macro, no?
I would still want to avoid repeating it in every `impl` but I currently don't see any way to do that :)



_Suggestion:_
```XML
macro_rules! implement_tx_account_params_getter {
    ($(($field:ident, $field_type:ty)),*) => {
        $(
            pub fn $field(&self) -> $field_type {
                tx.account_params().$field.clone()
            }
        )*
    };
}
```


<!-- Sent from Reviewable.io -->

2023-07-26 10:46 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaBdUjNDwBbQ7MLJC9V:-NaGiILkEUHC6_4Fv-GT:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b9897633df553b9740d43aaedd8202a9afca7cc4/src/transaction.rs#L80)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 125 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGZzJw5EMKzKKJCBQ1:-NaGnfB03SOJLOuxTbpL:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And then you can have one macro, no?
I would still want to avoid repeating it in every `impl` but I currently don't see any way to do that :)
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 269 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGE5DE5jd_BMi7_tGw:-NaGijDw32LZLRk0fEZO:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L269)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 274 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGDt4O8Zv4s5vkCYsN:-NaGinFx7-kNnOrSRR5C:b-ix5278) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L274)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is that the behaviour we want?
</blockquote></details>

Following our discussion, I've moved this method to `InvokeTransactionV2`.


<!-- Sent from Reviewable.io -->

2023-07-26 11:03 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 269 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGE5DE5jd_BMi7_tGw:-NaGq5uy4uhr-WxGHtWj:bw5tiyy) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L269)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

reverted.
`.clone()` on `Copy` types is usually not necessary, and you can simply use the value directly without any performance penalty.


<!-- Sent from Reviewable.io -->

2023-07-26 12:29 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 269 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGE5DE5jd_BMi7_tGw:-NaH7FwF4NdnL5bn5OEF:b-kd3dqd) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L269)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

reverted.
`.clone()` on `Copy` types is usually not necessary, and you can simply use the value directly without any performance penalty.
</blockquote></details>

Got it. Nice.
___
*[`src/transaction.rs` line 264 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHA3X7--28njZFIZy3:-NaHA3X7--28njZFIZy4:b-aqcceo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/c63642f4c1566a8d7911cf44d4978eb807177653/src/transaction.rs#L264)):*
> ```XML
>         match self {
>             Self::V0(_) => Err(StarknetApiError::InvalidTransactionNonce),
>             Self::V1(tx) => Ok(tx.account_params.nonce),
> ```

Putting it out here: maybe it's better to return an `Option<Nonce>` type and return `None` for V0.



_Code quote:_
```XML
    pub fn nonce(&self) -> Result<Nonce, StarknetApiError> {
        match self {
            Self::V0(_) => Err(StarknetApiError::InvalidTransactionNonce),
            Self::V1(tx) => Ok(tx.account_params.nonce),
```


<!-- Sent from Reviewable.io -->

2023-07-26 12:44 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 269 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaGE5DE5jd_BMi7_tGw:-NaHBVM45hvpehorPfnq:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4514afcb9a08d0c49938767933de59f1df6075ae/src/transaction.rs#L269)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Nice.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 264 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHA3X7--28njZFIZy3:-NaHDa_bDA8INnhBGwxP:b28b4o2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/c63642f4c1566a8d7911cf44d4978eb807177653/src/transaction.rs#L264)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Putting it out here: maybe it's better to return an `Option<Nonce>` type and return `None` for V0.
</blockquote></details>

I agree. It's better to return None.


<!-- Sent from Reviewable.io -->

2023-07-26 12:45 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)



<!-- Sent from Reviewable.io -->

2023-07-26 15:36 UTC, yair-starkware requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjOq45Rj_AnNk2fJu:-NaHjOq45Rj_AnNk2fJv:b-vdqfe5) (no related file):*
Can we avoid cloning in the getters?

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHm50-Brz8klV35V5h:-NaHm50-Brz8klV35V5i:bpsxc7n) (no related file):*
Not blocking, but IMO the macros here are getting out of hand.
Can we write a single macro that might be a bit more complicated but serves all of the structs and members?

___
___
*[`src/transaction.rs` line 337 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9iSY2r_yK1861IZj:-NaHp_D_1RkT46Gol51z:bb74ce2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L337)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add `sender_address`? (in invoke V0 it is the `contract_address` field)
WDYT @yair-starkware ?
</blockquote></details>

Sure
___
*[`src/transaction.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjlQu7YQL3LyQrSaL:-NaHjlQu7YQL3LyQrSaM:bmqm1mp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/83b373dc82ca9760ace005879f249900d8386e76/src/transaction.rs#L88)):*
> ```XML
>         (nonce, Nonce)
>     );
> }
> ```

Why do we need getters if the members are public and this is not a nested type? 



_Code quote:_
```XML
macro_rules! implement_account_params_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            self.$field.clone()
        })*
    };
}

impl AccountParams {
    implement_account_params_getters!(
        (max_fee, Fee),
        (signature, TransactionSignature),
        (nonce, Nonce)
    );
}
```
___
*[`src/transaction.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHoC0H91VyjssqJ4aZ:-NaHoC0H91VyjssqJ4a_:b-th2yas) ([raw file](https://github.com/starkware-libs/starknet-api/blob/83b373dc82ca9760ace005879f249900d8386e76/src/transaction.rs#L121)):*
> ```XML
>         )*
>     };
> }
> ```

Can the account params members be specified in the macro so they won't be specified in every macro invocation?



_Code quote:_
```XML
macro_rules! implement_tx_account_params_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(
            pub fn $field(&self) -> $field_type {
                self.account_params().$field.clone()
            }
        )*
    };
}
```


<!-- Sent from Reviewable.io -->

2023-07-26 16:24 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjOq45Rj_AnNk2fJu:-NaI-VrE9d737qNPJ6Wu:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we avoid cloning in the getters?
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHm50-Brz8klV35V5h:-NaI-cto8Yi6WFHOXk86:b2oq3wd) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not blocking, but IMO the macros here are getting out of hand.
Can we write a single macro that might be a bit more complicated but serves all of the structs and members?


</blockquote></details>

I'll consider creating such a macro and implementing it in a separate PR.

___
___
*[`src/transaction.rs` line 337 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaC9iSY2r_yK1861IZj:-NaHwmF05bhyEhGzn9jd:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cf96a71dfe70611645243b61372a8407c02c14d2/src/transaction.rs#L337)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjlQu7YQL3LyQrSaL:-NaHqgBLD27oEjNvAjw1:b-vpvas3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/83b373dc82ca9760ace005879f249900d8386e76/src/transaction.rs#L88)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need getters if the members are public and this is not a nested type? 
</blockquote></details>

Basically, for future versions, if we make changes to the code, such as adding a nested struct, there will be no need to modify the code in the Blockifier or Papyrus repository. WDYT?


<!-- Sent from Reviewable.io -->

2023-07-27 06:18 UTC, yair-starkware commented
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you make sure it doesn't break existing code in the blockifier?




<!-- Sent from Reviewable.io -->

2023-07-27 07:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjOq45Rj_AnNk2fJu:-NaLCUUb8p73TWTVF2tX:b5xmk20) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Did you make sure it doesn't break existing code in the blockifier?
</blockquote></details>

It breaks existing code. I've used deref/clone in the callers.

___


<!-- Sent from Reviewable.io -->

2023-07-27 07:25 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaLE6HI6QIWnhc7CQmR:-NaLE6HI6QIWnhc7CQmS:b-4me2ku) ([raw file](https://github.com/starkware-libs/starknet-api/blob/0e07bc190c422e1bd69cb7a70fd4659bed92cdd0/src/transaction.rs#L132)):*
> ```XML
>     ($(($field:ident, $field_type:ty)),*) => {
>         $(
>             pub fn $field(&self) -> &$field_type {
> ```

Why did you choose to return a reference now?



_Code quote:_
```XML
&$field_type
```


<!-- Sent from Reviewable.io -->

2023-07-27 08:05 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaLE6HI6QIWnhc7CQmR:-NaLJyEaDquA06bU-TmD:b-rwn2h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/0e07bc190c422e1bd69cb7a70fd4659bed92cdd0/src/transaction.rs#L132)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you choose to return a reference now?
</blockquote></details>

Following our discussion with Yair. We decide to avoid clone. In this case, we should use reference since some parameters, like TransactionSignature, doesn't implement Copy trait.


<!-- Sent from Reviewable.io -->

2023-07-27 10:21 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`src/transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaLE6HI6QIWnhc7CQmR:-NaLY1qYAIlw1kf3JRkt:b-k43l8u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/7f5b5f7d91051ad18bb3f0858332de646a381bc2/src/transaction.rs#L132)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Following our discussion with Yair. We decide to avoid clone. In this case, we should use reference since some parameters, like TransactionSignature, doesn't implement Copy trait.
</blockquote></details>

I'm not sure it's better. Isn't it weird(?) to return a copy-able type by reference? Can you please ask Alon why he chose to use `clone`? 


<!-- Sent from Reviewable.io -->

2023-07-27 11:03 UTC, yair-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjlQu7YQL3LyQrSaL:-NaM-E_M2PMVblZ4U9cU:bd45y6m) ([raw file](https://github.com/starkware-libs/starknet-api/blob/83b373dc82ca9760ace005879f249900d8386e76/src/transaction.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Basically, for future versions, if we make changes to the code, such as adding a nested struct, there will be no need to modify the code in the Blockifier or Papyrus repository. WDYT?
</blockquote></details>

It feels redundant, but I will resolve 


<!-- Sent from Reviewable.io -->

2023-07-27 11:41 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @yair-starkware)

___
*[`src/transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaLE6HI6QIWnhc7CQmR:-NaM8Yov9DmgtIEgn3TK:bcm6vrh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/7f5b5f7d91051ad18bb3f0858332de646a381bc2/src/transaction.rs#L132)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure it's better. Isn't it weird(?) to return a copy-able type by reference? Can you please ask Alon why he chose to use `clone`? 
</blockquote></details>

As discussed, I revert the "avoiding `.clone()`", since it goes beyond the scope of this PR.


<!-- Sent from Reviewable.io -->

2023-07-27 11:45 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-NaHjOq45Rj_AnNk2fJu:-NaM9SMi2y-Xd2VfM7WU:bggfvqb) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It breaks existing code. I've used deref/clone in the callers.
</blockquote></details>

As discussed, We keep using `.clone()` since it goes beyond the scope of this PR.

___


<!-- Sent from Reviewable.io -->

2023-07-27 11:51 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106#-:-NaMB6-k4mcuq1QQ_o1Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-07-27 11:53 UTC, yair-starkware approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-07-27 12:03 UTC, merged