Add nonce increment
starkware-libs/starknet-api pull request #142
Opened 2023-10-05 08:58 UTC by giladchase

Incrementing the maximum value in the field is 0.
Since this isn't good behavior for a nonce value, incrementing the maximum value is not allowed.

2023-10-05 09:05 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`src/core.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4UoP3rbw5bQ5m8kH:-Nfz4UoP3rbw5bQ5m8kI:b-p1r1zc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L142)):*
> ```XML
> 
> impl Nonce {
>     pub fn try_increment(&self) -> Result<Self, StarknetApiError> {
> ```

where is this used?



_Code quote:_
```XML
try_increment
```
___
*[`src/core.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3kSw8NJs_nnPcvQU:-Nfz3kSw8NJs_nnPcvQV:bvs8jvj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L143)):*
> ```XML
> impl Nonce {
>     pub fn try_increment(&self) -> Result<Self, StarknetApiError> {
>         let current_nonce = FieldElement::from(self.0);
> ```

not `Felt252`? when should we use which?



_Code quote:_
```XML
FieldElement
```
___
*[`src/core.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3uiL28kzxG5LmJtV:-Nfz3uiL28kzxG5LmJtW:b-i9wxhr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L151)):*
> ```XML
>             true => Err(StarknetApiError::OutOfRange { string: format!("{:?}", self) }),
>             false => Ok(Self(incremented_felt)),
>         }
> ```

`StarkFelt::ZERO` is const, right?



_Suggestion:_
```XML
        // Check if an overflow occurred during increment.
        match StarkFelt::from(current_nonce + FieldElement::ONE) {
            StarkFelt::ZERO => Err(StarknetApiError::OutOfRange { string: format!("{:?}", self) }),
            incremented_felt => Ok(Self(incremented_felt)),
        }
```
___
*[`src/core_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4L1y8249NFeSjXhe:-Nfz4L1y8249NFeSjXhf:b8wh298) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core_test.rs#L82)):*
> ```XML
> fn nonce_overflow() {
>     // Increment on this value should overflow back to 0.
>     let max_nonce = Nonce(StarkFelt::from(FieldElement::MAX));
> ```

isn't this what we use in tests? non blocking



_Suggestion:_
```XML
stark_felt!
```


<!-- Sent from Reviewable.io -->

2023-10-05 09:43 UTC, elintul requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`src/core.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-NfzCzg01UScex_W2Hyh:-NfzCzg01UScex_W2Hyi:b-x2itqs) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L146)):*
> ```XML
>         let incremented_felt = StarkFelt::from(current_nonce + FieldElement::ONE);
> 
>         // Check if an overflow occurred during increment.
> ```

Shouldn't the `StarkFelt` creation fail?



_Code quote:_
```XML
// Check if an overflow occurred during increment.
```


<!-- Sent from Reviewable.io -->

2023-10-05 09:54 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`src/core.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4UoP3rbw5bQ5m8kH:-Nfz6w9O7Km_xHdjcu9s:b-8qd8yu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

Will replace Blockifier's [CachedState's increment_nonce implementation](https://github.com/starkware-libs/blockifier/blob/7387447739fabb1df34d05ba7ee6e5ed79ddf47c/crates/blockifier/src/state/cached_state.rs#L281)
___
*[`src/core.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3kSw8NJs_nnPcvQU:-Nfz7CZlBbu9YtK8svdP:bfn4z7x) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L143)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not `Felt252`? when should we use which?
</blockquote></details>

I think that's in the cards, but right now SN API doesn't know about it yet, only FieldElement.
@elintul ?
___
*[`src/core.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-NfzCzg01UScex_W2Hyh:-NfzEeHo-AEI-DjC9rCS:bbsxxp6) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Shouldn't the `StarkFelt` creation fail?
</blockquote></details>

Nope, the field element also overflows back to zero.
___
*[`src/core.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3uiL28kzxG5LmJtV:-Nfz8z0x9TtLVirk_DLW:b-rzlpjx) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`StarkFelt::ZERO` is const, right?
</blockquote></details>

Yep, but do you think this is readable?
I did this somewhat awkwardly solely so that I can have a `is_overflow` label on it.
___
*[`src/core_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4L1y8249NFeSjXhe:-NfzFB_D47K93VQwNW9W:bt88k09) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core_test.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this what we use in tests? non blocking
</blockquote></details>

Changed.
Note that stark_felt! does a try_from + unwrap, not a `from` (which is generally not available when creating StarkFelt but is available for `FieldElement`).


<!-- Sent from Reviewable.io -->

2023-10-05 10:06 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-:-NfzIHkZ8hx8lMZqKD7v:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`src/core.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3uiL28kzxG5LmJtV:-NfzI2VfBRh8AigXxPKr:bqrarsl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L151)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, but do you think this is readable?
I did this somewhat awkwardly solely so that I can have a `is_overflow` label on it.
</blockquote></details>

I think the comment is enough, and `+ FieldElement::ONE` is pretty clear IMO.
If you don't know what finite fields are maybe you shouldn't be reading this code :P
Unblocking anyway, it's just style
___
*[`src/core_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4L1y8249NFeSjXhe:-NfzHhgw3fFkw4x6hmxS:b3uuleh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core_test.rs#L82)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Changed.
Note that stark_felt! does a try_from + unwrap, not a `from` (which is generally not available when creating StarkFelt but is available for `FieldElement`).
</blockquote></details>

hmmm... so maybe a better convension would be `from` when possible and `stark_felt!` when not / when inner objects are involved?


<!-- Sent from Reviewable.io -->

2023-10-05 10:25 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-:-NfzMjzeE5mOXQzbeavV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

___
*[`src/core.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3kSw8NJs_nnPcvQU:-NfzMcJxCedWP2TmKK9c:btzxbqo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L143)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think that's in the cards, but right now SN API doesn't know about it yet, only FieldElement.
@elintul ?
</blockquote></details>

Not sure what was decided in the end, but let's stick to the repo. convention.


<!-- Sent from Reviewable.io -->

2023-10-05 10:25 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-05 10:29 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-05 12:38 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-05 12:39 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`src/core.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz3uiL28kzxG5LmJtV:-Nfzov2W5d-q7_uLpnxN:bc26pmz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think the comment is enough, and `+ FieldElement::ONE` is pretty clear IMO.
If you don't know what finite fields are maybe you shouldn't be reading this code :P
Unblocking anyway, it's just style
</blockquote></details>

#gatekeeping :grimacing: 
Done.
___
*[`src/core_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-Nfz4L1y8249NFeSjXhe:-Nfzp3ZADnlPjFfoLlnH:b-bo3qze) ([raw file](https://github.com/starkware-libs/starknet-api/blob/136c6e46fe6f689313a38db2f2db8dc77a5508df/src/core_test.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... so maybe a better convension would be `from` when possible and `stark_felt!` when not / when inner objects are involved?
</blockquote></details>

There is also `StarkFelt::from_u128`, which is a const constructor (faster) and covers most of the current `stark_felt!` use-cases...
Not sure which is best :thinking: 

Reverting back to `from` for now.


<!-- Sent from Reviewable.io -->

2023-10-05 12:58 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142#-:-NfzueY7EJ217Isrra8o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-10 11:01 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-10 11:40 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-10 12:34 UTC, merged