feat(transaction): convert external to internal tx
starkware-libs/starknet-api pull request #230
Opened 2024-04-10 13:33 UTC by giladchase

- add `into_internal` method that consumes external tx and creates an internal (not using From in order to better emphasize the importance of this method in the API)
- refactor: remove repetition in docstrings.
- Add useful derives for internal txs.

Continuation of: https://reviewable.io/reviews/starkware-libs/starknet-api/222

2024-04-11 11:10 UTC, ayeletstarkware reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/230)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`src/external_transaction.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBF-ay6vxppg_4umuX:-NvBF-ay6vxppg_4umuY:btzvro0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/external_transaction.rs#L63)):*
> ```XML
>     pub fn into_internal(self, chain_id: &ChainId) -> InternalDeclareTransaction {
>         match self {
>             ExternalDeclareTransaction::V3(tx) => tx.into_internal(chain_id),
> ```

Are we sure we'll only see V3 transactions, or might others pop up and should be handled with an error?



_Code quote:_
```XML
V3
```
___
*[`src/external_transaction.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBVoZnAdP6R53gsjyo:-NvBVoZnAdP6R53gsjyp:bgzzwav) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/external_transaction.rs#L119)):*
> ```XML
> 
>         let tx =
>             crate::transaction::DeclareTransaction::V3(crate::transaction::DeclareTransactionV3 {
> ```

why not import that?



_Code quote:_
```XML
crate::transaction::
```
___
*[`src/internal_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBC9uf9DMehQJGpkfT:-NvBC9uf9DMehQJGpkfU:b-ag4qk0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/internal_transaction.rs#L8)):*
> ```XML
> 
> /// Represents a paid Starknet transaction.
> #[derive(Debug, Clone, Eq, PartialEq)]
> ```

please alphabetize


<!-- Sent from Reviewable.io -->

2024-04-14 11:04 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/230)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`src/external_transaction.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBF-ay6vxppg_4umuX:-NvRGiJlD2nx9IZCCwl4:b1ixx6w) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/external_transaction.rs#L63)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Are we sure we'll only see V3 transactions, or might others pop up and should be handled with an error?
</blockquote></details>

We'll have more, but remember that match is exhaustive, so once the enum has new variants this match will not compile, which is exactly what we want to happen.
(I hope I understood what you meant though :thinking: )
___
*[`src/external_transaction.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBVoZnAdP6R53gsjyo:-NvRGJqUEfuTO8-D11EB:btrhnyb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/external_transaction.rs#L119)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not import that?
</blockquote></details>

It might help clarifying what this is.
We already have ExternalDeclare, InternalDeclare, and now DeclareTransaction in the same scope, so _perhaps_ this might clarify what DeclareTransaction is referring to.

I'm not sure though... 
If there was just DeclareTransaction here, will it require a double-take in order to understand what this is? or is it immediately obvious?
___
*[`src/internal_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBC9uf9DMehQJGpkfT:-NvRGE1_94r-A2Qdn3H4:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/internal_transaction.rs#L8)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

please alphabetize
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 12:45 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/230)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvavvQa27dI3mAeiMqC:-NvavvQb6ecMwJRyVK22:b-88ua1v) (no related file):*
Please do not review this PR until we decide on the transaction type.

___


<!-- Sent from Reviewable.io -->

2024-04-16 12:48 UTC, ayeletstarkware reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/230)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`src/external_transaction.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/230#-NvBVoZnAdP6R53gsjyo:-NvawiL28ZltwCn2Y-uL:b-ewes68) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d891cf0669000d22b1f5974f7eff435450e1bc3b/src/external_transaction.rs#L119)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It might help clarifying what this is.
We already have ExternalDeclare, InternalDeclare, and now DeclareTransaction in the same scope, so _perhaps_ this might clarify what DeclareTransaction is referring to.

I'm not sure though... 
If there was just DeclareTransaction here, will it require a double-take in order to understand what this is? or is it immediately obvious?
</blockquote></details>

I think it's obvious here, but whatever you think.


<!-- Sent from Reviewable.io -->

2024-04-30 09:02 UTC, giladchase commented
Frozen for now pending future design review

2024-04-30 09:02 UTC, closed without merging