Class Hash
starkware-libs/starknet-api pull request #42
Opened 2023-03-30 09:00 UTC by marioiordanov

The PR includes:

- Implementation of v0 contract class hash computation
- StarkFeltAsDecimal struct, which serialises to decimal string when being used
- Usage of "preserve_order", "arbitrary_precision" of the serde json crate

2023-04-24 19:55 UTC, dan-starkware requested changes
Thanks, looks great, sorry for the long delay. Some general comments:
* Please separate into smaller PRs. (keccak, Felt as decimal, class hash)
* Please add documentation.
* Consider reordering code "from more to less interesting for a reader" (public before private, etc.) 
* Please add punctuation marks, specifically full stops, to comments.

> Reviewed 2 of 10 files at r1, 7 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-:-NTod6Ix8oe6bLE-FS_z:bgsvucw)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @marioiordanov)

___
*[`Cargo.toml` line 13 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTnYj6Q4qXI0vLjfM-4:-NTnYj6Q4qXI0vLjfM-5:bi46ubv) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/Cargo.toml#L13)):*
> ```TOML
> indexmap = { version = "1.9.2", features = ["serde"] }
> once_cell = { version = "1.16.0" }
> sha3 = "0.10.6"
> ```

Please use  `{ version = "0.10.6"}` for consistency. 



_Code quote:_
```TOML
sha3 = "0.10.6"
```
___
*[`src/core_test.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTn_Je71OstnR-NEZOj:-NTn_Je71OstnR-NEZOk:b-1mnt3u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core_test.rs#L70)):*
> ```XML
> 
> #[test]
> fn test_contract_class_hash_generation() {
> ```

Please remove `test_` prefix.
How did you get the expected class hash, please add a comment on that. 



_Code quote:_
```XML
test_contract_class_hash_generation
```
___
*[`src/core_test.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTnZpfN7NOQrMwENYc-:-NTnZpfN7NOQrMwENYc0:ba3dfna) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core_test.rs#L72)):*
> ```XML
> fn test_contract_class_hash_generation() {
>     let data_str = std::fs::read_to_string("./resources/contract_compiled.json").unwrap();
>     println!("{data_str}");
> ```

Remove?



_Code quote:_
```XML
println!("{data_str}");
```
___
*[`src/core_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTn_4NyCfbjAVqz6bHL:-NTn_4NyCfbjAVqz6bHM:b4bkgzl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core_test.rs#L73)):*
> ```XML
>     let data_str = std::fs::read_to_string("./resources/contract_compiled.json").unwrap();
>     println!("{data_str}");
>     let data: serde_json::Value = serde_json::from_str(&data_str).unwrap();
> ```

Consider renaming, maybe `contract_class`?



_Code quote:_
```XML
data
```
___
*[`src/deprecated_contract_class.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTnavYb3zqXJSr5Ckmb:-NTnavYb3zqXJSr5Ckmc:b-jk4dod) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/deprecated_contract_class.rs#L149)):*
> ```XML
>         Value::Number(number) => number
>             .as_u64()
>             .ok_or_else(|| DeserializationError::custom("Cannot cast number to usize."))?
> ```

Why the change?



_Code quote:_
```XML
        Value::Number(number) => number
            .as_u64()
            .ok_or_else(|| DeserializationError::custom("Cannot cast number to usize."))?
            as usize,
```
___
*[`src/hash.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToQesE3XR8Ty_29XTy:-NToQesE3XR8Ty_29XTz:b-og1u40) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L48)):*
> ```XML
> }
> 
> /// Starknet Keccak Hash
> ```

Can you please move to a separate PR?
Consider adding a reference to https://docs.starknet.io/documentation/architecture_and_concepts/Hashing/hash-functions/#starknet-keccak.



_Code quote:_
```XML
/// Starknet Keccak Hash
```
___
*[`src/hash.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToRrhIBidGaLsOtDGa:-NToRrhIBidGaLsOtDGb:b-57nlmw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L49)):*
> ```XML
> 
> /// Starknet Keccak Hash
> pub fn sn_keccak(data: &[u8]) -> String {
> ```

Consider `starknet_keccak`.
Please return a  StarkFelt.
Please add a test.



_Code quote:_
```XML
sn_keccak
```
___
*[`src/hash.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToR59d3DuqncKr6BVH:-NToR59d3DuqncKr6BVI:b-xmlkvh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L52)):*
> ```XML
>     let keccak256 = sha3::Keccak256::digest(data);
>     let number = U256::from_big_endian(keccak256.as_slice());
>     let mask = U256::pow(U256::from(2), U256::from(250)) - U256::from(1);
> ```

Consider a const/static.



_Code quote:_
```XML
let mask = U256::pow(U256::from(2), U256::from(250)) - U256::from(1);
```
___
*[`src/hash.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToUjoR2CG9gIlZ062Q:-NToUjoS4QdPJKz-oKq1:bywu5x1) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L66)):*
> ```XML
> 
> #[derive(Clone, Copy, Eq, PartialEq, Default)]
> pub struct StarkFeltAsDecimal(U256);
> ```

Can you please move to a separate PR?



_Code quote:_
```XML
pub struct StarkFeltAsDecimal(U256);
```
___
*[`src/serde_utils.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToWmTkBkKuXvhMeHJd:-NToWmTkBkKuXvhMeHJe:byy7l6m) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/serde_utils.rs#L131)):*
> ```XML
> use std::io;
> 
> use serde_json::ser::Formatter;
> ```

Move to the beginning of file / separate the section with a comment block?



_Code quote:_
```XML
use std::io;

use serde_json::ser::Formatter;
```
___
*[`src/serde_utils.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToWFbY4y9e24EaFU-R:-NToWFbY4y9e24EaFU-S:borreg2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/serde_utils.rs#L134)):*
> ```XML
> pub struct StarknetFormatter;
> 
> impl Formatter for StarknetFormatter {
> ```

Please document.



_Code quote:_
```XML
impl Formatter for StarknetFormatter {
```
___
*[`src/serde_utils_test.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToXYK01ZQU9aCOn5oX:-NToXYK01ZQU9aCOn5oY:bnxin9i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/serde_utils_test.rs#L114)):*
> ```XML
> 
> #[test]
> fn serde_deserialize_big_numbers_without_scientific_notation() {
> ```

What is this test for, arbitrary_precision feature? If so, please document. 



_Code quote:_
```XML
serde_deserialize_big_numbers_without_scientific_notation
```
___
*[`src/utils.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToffVXCHcrMHJymPtK:-NToffVXCHcrMHJymPtL:b2xx5y5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/utils.rs#L1)):*
> ```XML
> use serde_json::Value;
> ```

Consider moving `serde_remove_elements_from_json` test from `serde_utils_test` to `utils_test`.



_Code quote (from src/serde_utils_test.rs):_
```XML
serde_remove_elements_from_json
```
___
*[`src/utils.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NTocWzZ-6bIXnn54aAl:-NTocWzZ-6bIXnn54aAm:ba3dfna) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/utils.rs#L60)):*
> ```XML
> /// deserializing to a serde_json::Value changes the order of the keys
> /// Go through object's top level keys and remove those [...]

2023-04-27 07:33 UTC, elintul requested changes
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/42)* status: 9 of 11 files reviewed, 18 unresolved discussions (waiting on @dan-starkware and @marioiordanov)

___
*[`src/core.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0arPa0M9e9C4tYoR0:-NU0arPb3-Ae0w4lU1cj:b734tqi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L10)):*
> ```XML
> use once_cell::sync::Lazy;
> use serde::{Deserialize, Serialize};
> use serde_json::{json, Serializer, Value};
> ```

Consider using fully qualified names; `Value` is unclear.



_Code quote:_
```XML
use serde_json::{json, Serializer, Value};
```
___
*[`src/core.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0cJEHEqd2u-yqCyEo:-NU0cJEHEqd2u-yqCyEp:bs0baaw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L77)):*
> ```XML
> }
> 
> fn compute_class_hash_from_json(contract_class: &Value) -> String {
> ```

Why not getting a contract class object as input?
Where are you planning to call this function?



_Code quote:_
```XML
contract_class: &Value
```
___
*[`src/core.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0b0hXCRDmyFtu0hDQ:-NU0b0hXCRDmyFtu0hDR:bw69r5l) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L83)):*
> ```XML
>     });
> 
>     let program_json = abi_json.get_mut("program").expect("msg");
> ```

Informative error message?



_Code quote:_
```XML
"msg"
```
___
*[`src/core.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0b7h3-StMxk64X13z:-NU0b7h3-StMxk64X14-:b-seomqn) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L88)):*
> ```XML
>         program_json
>             .as_object_mut()
>             .expect("Not a json object")
> ```

In all strings.



_Suggestion:_
```XML
JSON
```
___
*[`src/core.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0biPE1qLbi8BGnGZJ:-NU0biPE1qLbi8BGnGZK:b-xrvqso) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L107)):*
> ```XML
>         Serializer::with_formatter(&mut writer, crate::serde_utils::StarknetFormatter);
>     res.serialize(&mut serializer).expect("Unable to serialize with custom formatter");
>     let str_json = unsafe { String::from_utf8_unchecked(writer) };
> ```

Is there an alternative for using `unsafe` code?



_Code quote:_
```XML
unsafe { String::from_utf8_unchecked(writer) }
```
___
*[`src/core.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0bJVr-Zs9fKt0xnNa:-NU0bJVs-c8B1wAloyi6:ba3dfmt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L108)):*
> ```XML
>     res.serialize(&mut serializer).expect("Unable to serialize with custom formatter");
>     let str_json = unsafe { String::from_utf8_unchecked(writer) };
>     println!("{}", str_json);
> ```

Remove.



_Code quote:_
```XML
println!("{}", str_json);
```
___
*[`src/core.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0bnkp2alr5WmhgPlO:-NU0bnkp2alr5WmhgPlP:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L111)):*
> ```XML
> 
>     let keccak_result = crate::hash::sn_keccak(str_json.as_bytes());
>     keccak_result
> ```





_Suggestion:_
```XML
    crate::hash::sn_keccak(str_json.as_bytes())
```
___
*[`src/utils.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0acUN3LRwa-OzXow-:-NU0acUN3LRwa-OzXow0:b-ltxqgu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/utils.rs#L3)):*
> ```XML
> use serde_json::Value;
> 
> /// because of the preserve_order feature enabled in the serde_json crate
> ```

Please separate to a preliminary PR(s). Same for all JSON utils.
PRs should be self-contained and consist of a single unit of logic (and a test).


<!-- Sent from Reviewable.io -->

2023-05-02 15:03 UTC, marioiordanov reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/42)* status: 9 of 11 files reviewed, 18 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`src/core.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0cJEHEqd2u-yqCyEo:-NURyLVW678t_Iuw9Dq4:b-cnzjj0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not getting a contract class object as input?
Where are you planning to call this function?
</blockquote></details>

because, when creating the json_object that will be hashed, there are keys in the Abi json property that are not part of the struct FunctionAbiEntry - state_mutability. So when hashing the json string created from object of type ContractClass and when hashing it created from json::Value, the result is different.


<!-- Sent from Reviewable.io -->

2023-05-03 09:49 UTC, marioiordanov reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/42)* status: 5 of 12 files reviewed, 18 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`src/core.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0cJEHEqd2u-yqCyEo:-NUVEofV3UxZyBfhLvNB:b-orq9a9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L77)):*
<details><summary><i>Previously, marioiordanov wrote…</i></summary><blockquote>

because, when creating the json_object that will be hashed, there are keys in the Abi json property that are not part of the struct FunctionAbiEntry - state_mutability. So when hashing the json string created from object of type ContractClass and when hashing it created from json::Value, the result is different.
</blockquote></details>

Also the order of the keys is essential, they should be in the order it is in the json file. When using the contract class the order of the keys is not guaranteed
___
*[`src/hash.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToQesE3XR8Ty_29XTy:-NUVqx2u8groC9LXqTP4:b-8ghqx9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L48)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you please move to a separate PR?
Consider adding a reference to https://docs.starknet.io/documentation/architecture_and_concepts/Hashing/hash-functions/#starknet-keccak.
</blockquote></details>

https://github.com/starkware-libs/starknet-api/pull/57
___
*[`src/hash.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToRrhIBidGaLsOtDGa:-NUVqwGX9yIik8sja1_R:b-8ghqx9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L49)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider `starknet_keccak`.
Please return a  StarkFelt.
Please add a test.
</blockquote></details>

https://github.com/starkware-libs/starknet-api/pull/57
___
*[`src/hash.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToR59d3DuqncKr6BVH:-NUVquz93yDSLdu8sTm8:b-8ghqx9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L52)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider a const/static.
</blockquote></details>

https://github.com/starkware-libs/starknet-api/pull/57
___
*[`src/hash.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NToUjoR2CG9gIlZ062Q:-NUVtmrE9uqaO9IGRLo-:b-8ghqx8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/hash.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you please move to a separate PR?
</blockquote></details>

https://github.com/starkware-libs/starknet-api/pull/58


<!-- Sent from Reviewable.io -->

2023-05-03 09:50 UTC, marioiordanov commented
Some of the requested changes about extracting to another PR are done, https://github.com/starkware-libs/starknet-api/pull/57 https://github.com/starkware-libs/starknet-api/pull/58

2023-05-05 10:11 UTC, LucasLvy commented
I see a lot of places where it can panic can you refactor it to have a better error handling ? We don't want anything to panic in the sequencer otherwise it's easy to attack the network

2023-05-07 09:08 UTC, yair-starkware commented
*[`src/core.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/42#-NU0cJEHEqd2u-yqCyEo:-NUpIp9L3xZ4xUuNGx_t:bfy6xbq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/211f3566d157c0d7896438ff91a566448e65a4bb/src/core.rs#L77)):*
<details><summary><i>Previously, marioiordanov wrote…</i></summary><blockquote>

Also the order of the keys is essential, they should be in the order it is in the json file. When using the contract class the order of the keys is not guaranteed
</blockquote></details>

IMO it is a must to implement the hash computation on the ContractClass struct as a method, and if needed, we should modify the struct and/or the feeder gateway so it will be possible.


<!-- Sent from Reviewable.io -->

2023-05-08 14:26 UTC, marioiordanov commented
> I see a lot of places where it can panic can you refactor it to have a better error handling ? We don't want anything to panic in the sequencer otherwise it's easy to attack the network

Done!

2023-05-08 14:43 UTC, marioiordanov commented
> IMO it is a must to implement the hash computation on the ContractClass struct as a method, and if needed, we should modify the struct and/or the feeder gateway so it will be possible.
@yair-starkware It is easy to be implemented, but that means the order of the properties of the struct should be alphabetically ordered, also the order of the inner structs should be as well, because the Cairo-lang compiler produces json file that is alphabetically sorted and If not sorted this way will produce different hash.

2026-07-03 05:25 UTC, closed without merging